#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.ityuan.sell.LoggerTest: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .template
    template-resolver-order:
    view-names:

   # 不传空参
  jackson:
    default-property-inclusion: non_null

  #redis配置
  redis:
    host: localhost
    port: 6379
    pool:
      max-wait: 1
      max-active: 8
      max-idle: 8
    database: 0

    #elasticsearch 配置
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true

server:
  context-path: /sell
